.TH "POINTS2ALLFINETRIANGS" "1" "@version@" "TOPCOM" "User Commands"
.SH "NAME"
points2allfinetriangs \- find all fine triangulations of a point configuration
.SH "SYNOPSIS"
.B points2allfinetriangs
[\fIOPTION\fP]...
.SH "DESCRIPTION"
.PP
Compute all fine triangulations of a point configuration.  Input is read from
stdin; output is written to stdout.  The standard options described in
\fITOPCOM\fP(7) are available.
.SH "EXIT STATUS"
.TP
0 if the points are read from stdin successfully.
.TP
1 otherwise.
.SH "SEE ALSO"
.PP
\fITOPCOM\fP(7),
\fIB_A\fP(1),
\fIB_A_center\fP(1),
\fIB_D\fP(1),
\fIcheckregularity\fP(1),
\fIchiro2allfinetriangs\fP(1),
\fIchiro2alltriangs\fP(1),
\fIchiro2circuits\fP(1),
\fIchiro2cocircuits\fP(1),
\fIchiro2dual\fP(1),
\fIchiro2finetriang\fP(1),
\fIchiro2finetriangs\fP(1),
\fIchiro2mintriang\fP(1),
\fIchiro2nallfinetriangs\fP(1),
\fIchiro2nalltriangs\fP(1),
\fIchiro2nfinetriangs\fP(1),
\fIchiro2ntriangs\fP(1),
\fIchiro2placingtriang\fP(1),
\fIchiro2triangs\fP(1),
\fIcocircuits2facets\fP(1),
\fITOPCOM-cross\fP(1),
\fITOPCOM-cube\fP(1),
\fITOPCOM-cyclic\fP(1),
\fITOPCOM-hypersimplex\fP(1),
\fITOPCOM-lattice\fP(1),
\fIpoints2alltriangs\fP(1),
\fIpoints2chiro\fP(1),
\fIpoints2facets\fP(1),
\fIpoints2finetriang\fP(1),
\fIpoints2finetriangs\fP(1),
\fIpoints2flips\fP(1),
\fIpoints2nallfinetriangs\fP(1),
\fIpoints2nalltriangs\fP(1),
\fIpoints2nfinetriangs\fP(1),
\fIpoints2nflips\fP(1),
\fIpoints2ntriangs\fP(1),
\fIpoints2placingtriang\fP(1),
\fIpoints2triangs\fP(1),
\fIpoints2volume\fP(1),
\fIsantos_22_triang\fP(1),
\fIsantos_dim4_triang\fP(1),
\fIsantos_triang\fP(1)
